### ISSUE TITLE
Proposal: add API based end-to-end (aka e2e) testing

### ISSUE THREAD

**Issue by LinuxSuRen** [goodrain/rainbond#1799]
### Is your feature request related to a problem?

Add the e2e testing proposal.

### Describe the solution you'd like

I'm the author of [api-testing](https://github.com/LinuxSuRen/api-testing) which is an API testing tool. It seems that no e2e testing in this project. I'd be happy to implement it if you believe it's worth it.

In order to let you have a quick knowing about it. Please see also the users of [api-testing](https://github.com/LinuxSuRen/api-testing/discussions/284).

**Comment by yangkaa** [comment]
Thanks for suggesting this feature. We are very interested in considering and adding end-to-end (e2e) testing to our tool. 

If possible, we would appreciate it if you could share your implementation plan and expected goals. This would help avoid unnecessary work and ensure alignment with our objectives. 

Any questions here; we are more than happy to provide answers.

**Comment by yangkaa** [comment]
Great, I believe you can implement it. However, before we start, I'm not sure how familiar you are with our project. The project mainly consists of the following components:

1. [rainbond-ui](https://github.com/goodrain/rainbond-ui): This is the user interface that users directly interact with.
2. [rainbond-console](https://github.com/goodrain/rainbond-console): It interacts directly with [rainbond-ui](https://github.com/goodrain/rainbond-ui), handling business logic operations and displays.
3. [rainbond](https://github.com/goodrain/rainbond): This is the core part of the entire project. It interacts with rainbond-console and ultimately generates corresponding resources in the cluster.

So, if you need to implement e2e testing, I believe the following parts are crucial:

1. Testing for the openapi provided by rainbond-console. This is important because when modifying the behavior of some interfaces, the methods called by openapi may be overlooked.
2. Testing for the application lifecycle management part of rainbond, such as starting, stopping and upgrade components.

If you need more information or have any other questions, I can provide further assistance.

**Comment by LinuxSuRen** [comment]
After some research, I found that it's not easy to setup the environment and application for the testing. I'm wondering if it's possible to have someone help me to setup the environment and make the application running. So, it will be much easier for me to write the E2E testing test cases.

**Comment by yangkaa** [comment]
![wechat](https://github.com/goodrain/rainbond/assets/30614084/31095e40-0bc3-471f-b252-e6c7b5cf5339)

You can add this WeChat and note "e2e test". I can ask others to help you set up the environment.

**Comment by ZhangSetSail** [comment]
由于这个issue已经有一段时间没有更新，我打算关闭它以保持项目的整洁。如果您在未来还有任何问题或需要进一步的帮助，请随时重新打开此issue或创建一个新的issue。
